### ISSUE TITLE
Button events

### ISSUE THREAD

**Issue by CristianLealRivero** [Silverethical/silverBox#1]
Hello, i am checking your magnificent library and i have a doubt. There is any option to check the events of the modal in the configuration of the modal? I know that i can use the ids of the elements to capture behaviours like click the cancel or confirm button but i wonder if there is an option of capture this events in the library

Thanks in advance!

**Comment by Silverethical** [comment]
Hello there. This is planned for v1.1.0 release along with some other nice features. So please keep watching for the next release and thanks for checking out the library :)

**Comment by CristianLealRivero** [comment]
Thanks a lot! I will be waitting for this new release

**Comment by Silverethical** [comment]
> Thanks a lot! I will be waitting for this new release

Sorry for the long delay, but it's finally here. The new version has been released. Enjoy :)

**Comment by girishvr** [comment]
Hi,
I have a question on similar line. How do I capture the input values once the "confirmButton" is clicked? I am able to call the "onClick" method but the input text values - I am not sure how to capture them. Basically, I need to make an HTTP call with the input values.

**Comment by Silverethical** [comment]
> Hi, I have a question on similar line. How do I capture the input values once the "confirmButton" is clicked? I am able to call the "onClick" method but the input text values - I am not sure how to capture them. Basically, I need to make an HTTP call with the input values.

Hi there. I thought maybe providing a working example might be better than me trying to explain it. So here is a working example. Let me know if there is any issues. @girishvr 

```js
silverBox({
  input: {
    name: "saber",
    value: "sword"
  },
  confirmButton: {
    closeOnClick: false,
    onClick: () => {
      // Select the input (or inputs) you need
      const saber = document.querySelector(".silverBox input[name='saber']")
      
      // Do stuff with their values
      console.log(saber.value);
    },
  },
});
```

**Comment by girishvr** [comment]
Thank you for you kind response. This helped.
